sudo: false
language: node_js
node_js:
- '6'
env:
  matrix:
  - GROUP=coverage
  - GROUP=packages
  - GROUP=lint
  - GROUP=flow
  - GROUP=conformance

cache:
  apt: true
  yarn: true
  directories:
    - node_modules

before_script:
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script: travis_retry yarn run test:$GROUP
after_success:
  - 'if [[ $GROUP == coverage* ]]; then bash <(curl -s https://codecov.io/bash); fi'
  - bash scripts/yarn.sh
