sudo: false
dist: trusty
language: node_js
node_js:
# Current Long Term Stable (LTS) release
- "6"
# Pending LTS
- "8"
env:
  matrix:
  - GROUP=coverage
  - GROUP=packages
  - GROUP=lint
  - GROUP=flow
  - GROUP=conformance

before_install:
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
before_script:
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
- greenkeeper-lockfile-update
script: npm run test:$GROUP
after_script: greenkeeper-lockfile-upload
after_success:
  - 'if [[ $GROUP == coverage* ]]; then bash <(curl -s https://codecov.io/bash); fi'
