# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:af7b81b839b0e11acc422e59ca52e42b3bb400f7246d81267d1217c89bc7ae07

    working_directory: ~/nteract

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - ~/.npm
            - ./node_modules
            - ~/.jestcache
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test:lint
      - run: npm run test -- --cacheDirectory=~/.jestcache
      - run: npm run test:flow
      - run: npm run test:conformance

      - run:
          name: Build Docs
          command: npm run docs:build

      - store_artifacts:
          path: styleguide
          destination: styleguide

      - run:
          name: Build Commuter
          command: npx lerna run build --scope @nteract/commuter
          no_output_timeout: 20m
      - run:
          name: Build Play
          command: npx lerna run build --scope @nteract/play
          no_output_timeout: 20m
      - run:
          name: Build Jupyter Extension
          command: npx lerna run build:asap --scope nteract-on-jupyter
          no_output_timeout: 30m
      - run:
          name: Build Desktop
          command: npx lerna run dist --scope nteract
          no_output_timeout: 30m
